name: Build and Publish Docker Image in Dockerhub

on:
  push:
    branches:
      - main 
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'README.md'

# env:
#   account: ${{ vars.ACCOUNT }}
#   container: ${{ vars.CONTAINER }}
#   image: ${{ vars.IMAGE }} 
#   account_2: deglanrivas

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
          ${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

# username: ${{ secrets.DOCKER_USERNAME }}
# password: ${{ secrets.DOCKER_PASSWORD }}
# ${{ vars.IMAGE_NAME }}
# ${{ vars.CONTAINER_NAME }}
# ${{ vars.PORT_MAPPING }}
# host: ${{ secrets.HOST }}
# username: ${{ secrets.USERNAME }}
# key: ${{ secrets.KEY }}
# port: ${{ secrets.PORT }}